### ISSUE TITLE
緯度経度の一括調査ツールを作りたい（GAS）

### ISSUE THREAD

**Issue by toon258** [CodeforKohoku/papamama#100]
「緯度経度の調査を一括更新したい！」と熱烈な要望が毎年出てきます。
ライセンス要件をクリアできる方法での開発にチャレンジしたい方は、ぜひ。
Google App Scriptで実装すると、運用しやすい形にできます。
　
参考）
　https://note.com/hal_sk/n/nc9df8b8fd765
　https://info.gbiz.go.jp/tools/imi_tools/

**Comment by yuukiw00w** [comment]
経済産業省が出したモジュールでも「大字町丁目」までらしいので、国の管轄内で出しているAPIだと番地以降の考慮はされてない可能性ありそう
https://qiita.com/nyampire/items/d74dcde6e57f793ab0c1

精度の高いAPI（GoogleのようなAPI）の大本になる地図情報はゼンリンのような企業が整備して販売している有料販売物なので、無料で誰でも使えるような範囲では精度の高いAPIが存在しない可能性がありそう

GoogleのジオコーディングAPIは使いすぎると有料なので使えない

YahooのジオコーダAPIが無料で使えそうならよさそうなので調査したが、商用利用じゃなければ大丈夫そうな感じはあるけど、悩ましいので心配なので一旦保留

**Comment by yuukiw00w** [comment]
参考URLのやつも
> 精度は「大字町丁目」までとなっているため、商用のジオコーディングサービスに比べると精度は低いです。
とのことなので、番地以降考慮されてない

**Comment by yuukiw00w** [comment]
yahooは個人利用じゃないから駄目っぽい
https://developer.yahoo.co.jp/webapi/map/
ユーザーが非営利かつ個人利用（第三者頒布は不可）の目的を超えて複製物を作成および利用（複製物の営利もしくは法人での利用または第三者への頒布を目的とする利用を含むがこれらに限られない）する場合、YOLPにより提供される情報の著作権者と複製物の利用に関する契約を締結し、当該複製物の利用に関する複製利用料を当該著作権者に別途支払わなければならないものとする。

**Comment by yuukiw00w** [comment]
GoogleのジオコーディングAPIの利用規約
https://cloud.google.com/maps-platform/terms/?_ga=2.77136853.1989039706.1621748148-595177062.1602502673#3.-license.

**Comment by yuukiw00w** [comment]
結論としては一括で自動取得は無理そう
単純にスプレッドシート上で該当住所の地図urlを自動生成して、そこから地図を確認しにいって、確認した緯度経度を反映するフローにする方が良さそう

**Comment by yuukiw00w** [comment]
https://kohoku.slack.com/archives/C3DQMF9UG/p1621752253015100

> マップデータ入力シートに、地図linkというシートを追加しました
> そこに保育園とかの住所を自動で反映して、Google Mapのurlを生成するようにしてあります
> 今後はここで地図を開いて住所チェックしたあと、緯度経度を確認したら作業シートに反映するフローにできるといいかなと思います
> https://docs.google.com/spreadsheets/d/1HCCg2KcCZJubghX-846Y4K9P3EbKIA1mO2Pgv006kIg/edit?ts=60a9f373#gid=420741928

こちらの対応で代替することになったので一旦close
