### ISSUE TITLE
検索機能の内容の検討

### ISSUE THREAD

**Issue by homata** [CodeforKohoku/papamama#11]
●検索機能
⇒内容検討、要変更
（柿木さんが対応予定）

**Comment by chikarina** [comment]
kakaikidropさん　先日の勉強会で話した内容でのページを今月中に作れそうですか？

**Comment by kakikidrop** [comment]
了解です。
確認事項については別途確認させてください。

**Comment by kakikidrop** [comment]
すみません。
元々の検索自体が正しく動いてないようで（プログラムのせいかデータのせいか私の腕の問題か…）、
検索周りのプログラムの確認に時間がかかっております。
すみませんが今週いっぱいお時間をいただけないでしょうか？

**Comment by kakikidrop** [comment]
柿木です。
取り急ぎ、現時点で下記の問題点があります。
-----------------------------------------------------
[不具合]
・最寄駅・円消去について
　　マウスを動かさないとリストの文字色が黒くならない

〇検索
・検索画面内のリストボックスの文字色が白抜きのまま（背景などのリストボックスと同じ処理をする必要がある）

・各検索条件に合致する正しいデータが表示されない
　＊開園/閉園時間
　　条件に合致するデータがある時はその保育園のみが正しく表示されるが、合致するデータがない場合は全保育園が表示される（何も表示されないのが正しいはず）
　＊他ボタン条件（一時保育/夜間/休日/空きあり/証明書/２４時間）
　　どれを押しても全保育園が表示される

・検索した後に検索画面を閉じないで他条件を再入力すると、前の条件が残ってしまっている

・開園/閉園時間の検索条件がソース埋め込みになっている（※検索条件セット時に時間の文字列を埋め込みしている為）。
その為、新しい開園/閉園時間の保育園や、閉園時間が２４時をまたぐ保育園が表示されないと思われる。
　※検索条件セット時に時間の文字列を埋め込みしている為。
　　データでの開園時間/閉園時間の入力ルールを統一するか、
　　検索側での条件設定を埋め込みではない形（できれば日付/時刻型で比較する形）に修正する必要がある。

[確認点]
・検索条件：認可外の「証明書あり」は港北区版には要りますか？
-----------------------------------------------------

**Comment by kakikidrop** [comment]
すみません。上記の太字には意味はありません…

**Comment by chikarina** [comment]
柿木さん
確認ありがとうございます。
作ってもらったページをｐｕｌｌリクエスト？してもらうことは
可能でしょうか？

確認点：認可外の「証明書あり」は港北区版には要りますか？
個人的に現時点では**「いらない」**
と思います。よろしくお願いいたします。

**Comment by kakikidrop** [comment]
検索画面対応が完了しましたのでpushしました。
確認をお願いいたします。
※スマホでの動作は未確認なので後ほど確認が必要と思われます。

以下、変更内容です。

**************************************
・検索条件に横浜保育室を追加しました。
・開園時間/閉園時間の検索内容を変更し、検索画面上の全保育園（公立認可/私立認可/認可外/横浜保育室）で統一しました。
・認可外の「証明書あり」を検索条件から削除しました。
・検索画面レイアウトを少し変更しました（公立認可/私立認可/横浜保育園の「一時保育/夜間/休日」を開園/閉園時間の下から横に移動しました）。

**Comment by chikarina** [comment]
柿木さんがpullrequestしてくれています。
どうぞよろしくお願いいたします。
