### ISSUE TITLE
園名が出ている園出ない園の違いは？

### ISSUE THREAD

**Issue by homata** [CodeforKohoku/papamama#13]
園名が出ている園出ない園がある
-> 要確認

**Comment by toon258** [comment]
→原因判明
「label1」に入力した名称が地図に表示されているので、
「label1」が空欄・「Name」のみ入力ありのデータが「地図上に園名が出ない」状態になっています

**Comment by homata** [comment]
元のスプレットシートを更新する

**Comment by toon258** [comment]
スプレッドシートの更新、マップへのデータ反映完了しました！
