### ISSUE TITLE
小規模・事業所内保育事業 を追加

### ISSUE THREAD

**Issue by chikarina** [CodeforKohoku/papamama#14]
小規模・事業所内保育事業　の分類を追加
・私立の右隣に
・色は保育園系統の色希望（緑系）

よろしくお願いいたします。

**Comment by toon258** [comment]
分類追加しました！
確認お願いします~

**Comment by chikarina** [comment]
メイン画面の園の種類のところは
「小規模等」に変更お願いしたいです。
（いま「事業所等」となっているところ）
よろしくお願いいたします。

**Comment by toon258** [comment]
@chikarina メイン画面の園の種類の変更、対応しました~！
