### ISSUE TITLE
園の情報更新

### ISSUE THREAD

**Issue by homata** [CodeforKohoku/papamama#15]
●園情報
・４月に認可移行園。新設園
・アンティー妙蓮寺、　グローバルキッズ菊名　移転・認可移行

**Comment by kakikidrop** [comment]
・未着手
　No.81-88、133-147

**Comment by wankyo1010** [comment]
・未着手（No.81-88、133-147）は、6/18に分担して作業済
・アンティー妙蓮寺、グローバルキッズ菊名→住所変更、私立認可保育所に修正済み

（追加）
・未入力項目がある（No.120-107、No.153、155、157、159）
・アンティー妙蓮寺について、No100とNo128はデータが重複している？
・みらいく日吉本町園、大曽根コスモス保育園が抜けている
・「20170618完成版」のデータ件数とびーのガイド（2018年度入園版）の件数が不一致
　（※詳細は「課題」シートに記載しています）

（懸念点）
・移転や誤記修正で、住所を変更した場合に座標の修正もセットで行わないと整合性が取れなくなるのでは？

**Comment by chikarina** [comment]
2018/1/18 　完了確認
