### ISSUE TITLE
(?)のリンク先とREADMEについて

### ISSUE THREAD

**Issue by wankyo1010** [CodeforKohoku/papamama#19]
リンク先を
https://github.com/CodeforKohoku/papamama
に修正していただきましたが、ダイレクトにREADME.mdを表示したほうが
初めて見る方にとっては分かりやすいのかと思いました。
https://github.com/CodeforKohoku/papamama/blob/master/README.md

READMEに使い方の記載が必要だと思います。
※さっぽろのページを参考に文章を作成しました

■使い方
・港北区内の保育所、幼稚園を表示します。
　　「公立認可・私立認可・横浜保育室・認可外」は、保育園の位置情報
　　「幼」は、幼稚園の位置情報
・「保育園のアイコン」をクリックすると開園時間などの情報を表示します。
・公立の小学校・中学校の学区を保育園と重ねて表示します。
　　「小」は、小学校区
　　「中」は、中学校区
・「検索」から様々な条件で保育所の絞り込み表示をします。　※実装状況次第
・「背景」から地図の種類を変更することができます。
・「最寄駅」を中心に表示します。
・「検索」から様々な条件で保育所の絞り込み表示します。
・「円消去」は中心位置から選択した距離の半径を表示します。
・「？」はこの説明（README)です。

**Comment by hatanakayumiko** [comment]
村岡さんありがとうございます、昨夜何がいいのか、悩み悩み、小俣さんとつくっていました。
小俣さん、村岡さんのご意見いかがですか。利用者目線を第一に考えたいと思いますが、ダイレクトにREADMEのところを出すことができますか。

**Comment by toon258** [comment]
ダイレクトにREADME.mdを出すと、↓のような見え方になります！

https://github.com/CodeforKohoku/papamama/blob/master/README.md

**Comment by homata** [comment]
ダイレクトにREADME.mdは簡単は出せます。決めの問題で、何を目的にするかですね。

README.mdでいいのか悪いのか？それともホームページがいいのか？などですね。

**Comment by hatanakayumiko** [comment]
README.mdが先に見えることで何かわるいことがありますか。←文字だけだと感じわるそうなコメントですが、それが不自然なことなのか、特に差し障ることがあるのかどうか、ということです。

利用者目線では　？　を押すときは、これどうやって使うの？っていうときだと思います。
使い方が一番読みたい。

そうすると、READmeとは別に、使い方を記した、新しいページをつくったほうがいいということになりますか。

**Comment by hatanakayumiko** [comment]
村岡さん、他のCODE forの保育園マップを一通りみてみて
どんな感じだったらいいと思いますか
https://www.facebook.com/groups/899405606784700/

**Comment by wankyo1010** [comment]
私としては、つくば保育園マップが利用者目線では一番よいと思います。
https://shamrock3ire.github.io/
（右上のSocial・Tags・Linksなどの箱は不要で、単純なHTMLイメージ）

理由としては
１）畑中さんが書かれているとおり、使い方が一番見たい。それに加え、更新履歴もある
２）別のＨＰではなく、GitHub上にページが作られているので管理が1箇所となる
３）今のリンク先やREADME.mdをダイレクトに表示した場合、GitHub自身のリンク
      (上部のIssuesとかPullrequestsとかに触ってしまって、何のページ？！と
　　驚かせることがない）

README.mdをダイレクトに表示し、冒頭の説明の次に使い方をいれる、という
方法ではダメですか？
３）の問題は残りますが、メンテナンスが容易ですので。

**Comment by wankyo1010** [comment]
howto.htmlというページを試しに作成してみました。どうでしょうか？
README.mdの内容に使い方など、少し文章を加えました。
git push までしたのですが、その後の操作がよくわからず。。。です。

あと、README.mdで気になったことですが、冒頭では
「港北区　オープンデータを活用した子育て情報サービス検討プロジェクトによって開発された保育園マップ」
と書かれていますが、末尾では
「Codefor港北によって開発されたもの」
となっているので、OKPとCodefor港北の関係性がわかりにくいなと思いました。

**Comment by hatanakayumiko** [comment]
関係性の明示ですね

README.mdの文章に付け足す形がいいと思います。

今のCodefor港北の保育園マップ
GitHubで公開されているさっぽろ保育園マップを元に港北区　オープンデータを活用した子育て情報サービス検討プロジェクトによって開発された保育園マップです。

↓ここから追記
港北区オープンデータを活用した子育て情報サービスプロジェクトは、2015年年度から横浜市港北区役所と港北区地域子育て支援拠点どろっぷとその利用者有志によって、新たな子育て情報提供を検討するために取り組みを開始しました。
その中で、さっぽろ保育園マップアプリに出会い、横浜市港北区における保育園マップ開発に取り組むにあたり、プロジェクトメンバーを中心にCodefor港北（kohoku）のチームができました。←ここまで

でどうですか。
わかりやすくなりましたか
長いですか？

**Comment by wankyo1010** [comment]
関係性を明示することで分かりやすくなったと思います！
howto.htmlに上記の文章を追加し、git push までしました。
なお、「検索」機能に関しては「※未実装」と記載してあります。

**Comment by toon258** [comment]
@wankyo1010 反応遅れてしまい、すみません。
村岡さんのブランチからmasterに変更を取り込みました！
トップページの「？」リンクの向け先変更も対応済みです。
