### ISSUE TITLE
「保育園マップ」のタイトルについて

### ISSUE THREAD

**Issue by wankyo1010** [CodeforKohoku/papamama#20]
「保育園マップ」のタイトルですが港北区としては「保育園幼稚園マップ」なのですよね？
3/11の案内で「保育園幼稚園マップ」と謳っているので気になりました。
後者なら、全般に名称の修正、検索は「保育園検索」などの修正が必要となってくると思います。

**Comment by hatanakayumiko** [comment]
村岡さん、そもそものところでしたね、そうですね。なんで気づかなった今まで！と己をのろいます。が今そこ直しだすとキリがない。とすれば、これはエンハンス対応とするのがいい気が私はします。 #

**Comment by kakikidrop** [comment]
タイトル名を「Codefor港北　保育園/幼稚園マップ」に変更。
※畑中さん的には”Codefor港北”を先頭に持ってくるのは必須！とのこと

最終的なタイトルは放課後デイや学童を追加する際に検討すること。
