### ISSUE TITLE
幼稚園・保育園データ入力シート入力時のお願い

### ISSUE THREAD

**Issue by toon258** [CodeforKohoku/papamama#21]
データ再作成にあたり幼稚園・保育園データ入力シートを一部修正しましたので、
修正内容の共有と今後の更新にあたってのお願いをまとめます。

**■変更点**
「20161122完成版」シートに
・フィルタを追加しました。
・右端に「fX」列、「fY」列を追加しました。
　※ここにデータの住所情報をもとにGeoCodingというサイトから取得してきた
　　緯度経度を入力しています。

・右端に「緯度経度修正あり」列を追加しました。
　issue #5 で個別の園ごとに緯度経度を調べて修正していただいたデータを判別するために、
　修正した分に「Y」を入力しました。

・「Y」列、「X」列
　上述の修正分以外にGeoCodingで調べたデータ（「fX」列、「fY」列と同じ値）を入力しました。

**■データ更新時のお願い**
・初期のデータ入力では
　「Y」列、「X」列には何も入力しない状態にしてください。

　※データをマップに反映するとき、GeoCodingで緯度経度を調査します。
　　GeoCodingの結果は「fX」列、「fY」列に貼り付け
　　差分だけを「Y」列、「X」列に反映する
　　（……という更新方法がいいかな？）

・手動で緯度経度のデータを修正したときは
　「Y」列、「X」列に修正後の緯度経度を設定のうえ、
　「緯度経度修正あり」列に「Y」を入力してください。

・セル内部には改行が入らないようにご注意ください。

　参考：GeoCoding
　http://newspat.csis.u-tokyo.ac.jp/geocode-cgi/geocode.cgi?action=start

**Comment by chikarina** [comment]
ありがとうございます。
スプレッドシートにＵＲＬを追加したのですが、
この際もＹ，Ｘ列を一度空欄にした方がよろしいのでしょうか？

**Comment by toon258** [comment]
いえ、すでに埋まっているところはそのままにしていただいて大丈夫です！

新規でデータを追加する際に、Y,Xが空白のデータがあればGeoCodingが必要だとわかるようにしておきたいと思っています。
