### ISSUE TITLE
認可外の監督基準の項目について

### ISSUE THREAD

**Issue by chikarina** [CodeforKohoku/papamama#22]
認可外保育園の「詳細」を押すと
札幌マップに飛んでしまうため、この項目自体の
削除をお願いします。

**Comment by toon258** [comment]
@chikarina 「(詳細)」の文言のみ削除しました。
対応してからあれ、と思ったのですが、もしかして
この項目自体＝「監督基準	証明書発行済(詳細)」の一行を削除
……ということでしょうか？

ちなみにデータの「Proof」列に
入力があれば「証明書発行済」を表示する、入力がなければ表示しない、
という出し分けができます（今はバグで全件表示されていますが…）

**Comment by chikarina** [comment]
ありがとうございます。

この項目自体＝「監督基準 証明書発行済(詳細)」の一行を削除

をお願いします。
お手数おかけしてすみません。

**Comment by toon258** [comment]
対応完了しました！
