### ISSUE TITLE
Papamamap.jsのaddNurseryFacilitiesLayerについて

### ISSUE THREAD

**Issue by kakikidrop** [CodeforKohoku/papamama#24]
すみません、どなたか教えてください。

Papamamap.jsのaddNurseryFacilitiesLayerで最初に行われているremoveLayerについて、
表示するレイヤー数とremoveLayerしている数が合わなくて検索表示時に不具合がでていた為、
        this.map.removeLayer(this.map.getLayers().item(4));
を２行分追加し、表示するレイヤー数と合わせました(修正ファイルは現在pushまでしています)。
この時、↑のitem(4)もitem(6)に修正するのが正しかったでしょうか？
※動作確認した時にはitem(4)のままでも問題なかったので、pushしたPapamamap.jsではitem(4)のままにしています。

分かりにくくてすみません。
不勉強で申し訳ないのですが、分かる方がいらしたら教えてください。

**Comment by toon258** [comment]
@kakikidrop 柿木さん、気付くの遅れてしまってすみません！
これ、保育園区分を追加したときに直しておくべきでしたね。ご対応ありがとうございます。

ご対応いただいた通り、
this.map.removeLayer(this.map.getLayers().item(4));
の行数を増やしてカッコ内の数字は4のまま、というのが正しい対応かと思います。

ソースコードが少しわかりにくいのですが、ソースを「getLayers().item」で検索してみるとitem内の番号はそれぞれ下記のレイヤーと対応しているようでした。
　item(0)：地図画像
　item(1)：中学校区
　item(2)：小学校区

（item(3)が何にあたるのかは、ちょっとよくわかりませんでした…）

addNurseryFacilitiesLayerメソッドでは
item(4)以上があればいったんremoveしてきれいにしてから、レイヤーを追加する、ということをしているので、レイヤーの数だけitem(4)の削除を繰り返す…という方法で問題ないのかな、と思います。

よろしくお願いいたします。
