### ISSUE TITLE
隣接市区との保育園情報の連携について

### ISSUE THREAD

**Issue by kakikidrop** [CodeforKohoku/papamama#33]

**Comment by chikarina** [comment]
都筑、鶴見、神奈川区、緑区との連携をすすめる
※UDC

**Comment by hatanakayumiko** [comment]
アーバンデータチャレンジでは、他自治体との連携での活動、データ作りが必要です。都筑区、鶴見区、緑区、神奈川区の園情報を入れ込むことで、コンテストへの出品も狙っていきたいと思っています！
上記は港北と隣接区となり、子育て支援拠点同士の連携のなかで、ともに活動できると思っています、施設長間、担当者間でも話としてはあったらいいよねが共有されています。詳細な連絡をしていこうと思います。

**Comment by toon258** [comment]
2019/1/13 鶴見区のデータを入力！
タイトル変更など要対応
