### ISSUE TITLE
スマホでの表示について

### ISSUE THREAD

**Issue by kakikidrop** [CodeforKohoku/papamama#41]
PCに合わせると、公立認可～？の表示が複数行になってマップ自体が見にくい。
アクセスがＰＣかスマホかでタイトルと公立認可～？の表示サイズを変更することはできないか？

**Comment by kakikidrop** [comment]
参考：
http://www.yuta-system.com/homepage/pccss1.html

**Comment by chikarina** [comment]
現状維持
項目が増える際に再検討
