### ISSUE TITLE
幼稚園の画面内容について

### ISSUE THREAD

**Issue by kakikidrop** [CodeforKohoku/papamama#42]
内容について要検討。
例／プレがあるか、バス通園ありか　等

**Comment by kakikidrop** [comment]
5/21に出た内容
・プレの有無
・預りの有無
・バス通園の有無
・給食の有無
・（曜日によって違う）保育時間の表示について

**Comment by kakikidrop** [comment]
上記項目について追加するか・その実現方法について検討が必要。

**Comment by toon258** [comment]
・幼稚園の表示項目を保育園と統一するか（現在は差異あり）検討

**Comment by chikarina** [comment]
延長保育の欄に預かり保育を入れる
・バス、プレ、給食
→最終的には有無のみキーでほしい
→取り急ぎ備考に追記
　備考に給食は週〇回表記

**Comment by toon258** [comment]
@chikarina さん、
> 延長保育の欄に預かり保育を入れる
なんですが、データの「Extra」の欄を延長保育有無として使いたいということだと、
#50 と矛盾するかと、、

Extraと同じように、預かり保育の欄を追加するという対応がいいかと思いますが、どうでしょうか？

**Comment by toon258** [comment]
また、項目を追加するならデータ変換用のツールも直す必要があるので、欲しい項目があれば一気にやってしまいたいです。
バス、プレ、給食は今後使う可能性が高いのであれば、
今回項目を追加してしまったほうがいいのかなーと思います。

**Comment by hatanakayumiko** [comment]
江口さん、幼稚園のデータをいじるとき、延長保育の園独自型と、神奈川県型ってなにをみればわかるんでしたっけ？
びーの幼保ガイドで、延長保育の欄に幼稚園型と横浜市型はありますね。
①延長保育の欄に●型表記なしで、記入のあるのは、園独自型でいいか？
②延長保育の欄に、幼稚園型と、横浜市型両方あるところ、例えば都筑が丘幼稚園のところはどうしたらいいか
③銀嶺幼稚園P62は型の記入なしで、園長保育の表記がある。←これは園独自型、でいいか。

**Comment by hatanakayumiko** [comment]
備考欄に併記型含めメモで記載する。参考資料＞幼稚園保育園ガイド2018版P36　幼稚園キーワード集、
及び各園ページ

**Comment by toon258** [comment]
他issueにて対応済
