### ISSUE TITLE
円表示に関して　地点の指定について

### ISSUE THREAD

**Issue by hatanakayumiko** [CodeforKohoku/papamama#48]
拡張機能として、
A地点、B地点がいれられて、半径で検索ができる。
 今は必ず中心から距離円をいれるようになっている。
それはもった上で、

新たな機能として、任意の２か所を選んでその直線状に□ででるような範囲表示があるといい

**Comment by chikarina** [comment]
・ピンを立てたい
・中心からの距離を刻む
　５００・１K・２K・３K

２点については今後の様子で再検討
