### ISSUE TITLE
園の位置情報に誤差がある

### ISSUE THREAD

**Issue by toon258** [CodeforKohoku/papamama#5]
緯度経度を修正する

●園情報（大幅な位置の違い）
・岸根保育園　、菊名保育園　、ポピンズナーサリー小机　
・岩崎学園新横浜園　、オハナ新羽　、ベネッセ日吉
・キッズラディ、SUNSUN・ウッズの重なり
・まめどくれしゅ、キッズラディの文字が被っている（住所間違い？）

・位置のずれ：エジュケア保育園、リトルスカラー妙蓮寺　、菊名愛児園
うみのくにきくな、　森の樹、ヒューマンアカデミー大倉山
くっくふとお、わおわお、なあな、新羽どろんこ、日吉こども園

・幼稚園の若干の位置ずれ（地図をズームにすると園の場所がずれている）
数センチ動かしたい
⇒位置情報をずらすのではなく、「表示位置をずらす」

**Comment by homata** [comment]
位置情報は少量であれば修正先の緯度経度の座標がわかれば比較的に簡単に修正できます。
地理院地図を使って、新しい緯度経度の座標をまとめておいていただればありがたいです

**Comment by tamano3** [comment]
えと、すみません。
非常に初歩的な質問で申し訳ないのですが
緯度経度って
世界測地系と日本測地系の
何方でしたっけ？

**Comment by chikarina** [comment]
スプレッドシート上に地理院地図から緯度経度を追記しました。

**Comment by toon258** [comment]
@chikarina さん、マップのデータを更新しました。
念のため、表示位置が問題ないかご確認おねがいします！
