### ISSUE TITLE
参照データのアーカイブについて

### ISSUE THREAD

**Issue by hatanakayumiko** [CodeforKohoku/papamama#52]
参照データのアーカイブについて
マップデータを入力した際に参照したURL文献ETCとの根拠をどこにもつか？
の決め事、ルールを決めたい。
→再チェック時のコストダウンのために。やり直しのときにどこにあたるかを明確にしたい。

**Comment by hatanakayumiko** [comment]
エンジニア・開発ベースの話。
スプレッドシート　URL参照サイト・優先順位のシートを参照することに決める。

**Comment by chikarina** [comment]
スプレッドシート修正で完了
あまのさんの部屋が引っ越しました
