### ISSUE TITLE
営業時間帯の多様性の対応

### ISSUE THREAD

**Issue by hatanakayumiko** [CodeforKohoku/papamama#53]
営業時間帯対応の多様性の対応　
営業時間帯がかなり多岐にわたる？

**Comment by hatanakayumiko** [comment]
保育園は最大保育時間だけでよい。
幼稚園は、標準保育時間をいれる。備考で水曜午前保育、延長保育有無。延長保育の種類などを記入する。
へるぷ欄には、その旨記載する。

**Comment by chikarina** [comment]
2018/1/18　完了確認
ヘルプ欄対応
