### ISSUE TITLE
分園問題

### ISSUE THREAD

**Issue by hatanakayumiko** [CodeforKohoku/papamama#55]
分園がかなり存在する
別々の表記でよいか。

**Comment by hatanakayumiko** [comment]
分園は個別に住所はいれる。
園名表記はびーの幼稚園保育園ガイドに準じる
内容は住所以外は同一。

**Comment by hatanakayumiko** [comment]
ヘルプの欄には、分園については住所以外は本園と同じ内容で掲載しています、をいれることにする。

**Comment by chikarina** [comment]
2018/1/18　完了確認
