### ISSUE TITLE
タイトルの修正

### ISSUE THREAD

**Issue by wankyo1010** [CodeforKohoku/papamama#57]
タイトルが「Codefor港北保育園マップ」のままなので、「/幼稚園」の追加が必要
※検索エンジンでの表示されるのがタイトル部分なので。。。

また、HELPのページも同様に修正が必要。
※タイトル部以外にも何箇所か修正＆機能追加に伴う修正も。

**Comment by wankyo1010** [comment]
HELPのページについては、6/18に修正版を作成し、git pushまでしました

**Comment by chikarina** [comment]
画像に置き換え希望。それをバナーにもしたい。

**Comment by toon258** [comment]
鶴見区のデータ追加につき、「港北区周辺」的なタイトルに変更したい
