### ISSUE TITLE
ポピンズナーサリースクール綱島の住所変更

### ISSUE THREAD

**Issue by toon258** [CodeforKohoku/papamama#58]
ポピンズナーサリースクール綱島の住所変更を反映する。
https://www.poppins.co.jp/nursery/room/detail/6784/

※幼稚園・保育園マップにて、園のチェック漏れで開園前の旧地番を掲載している。
びーののホームページでお詫びを掲載して訂正しており、マップのデータも修正したい。

旧：横浜市港北区綱島東3-1445（地番）
新：神奈川県横浜市港北区綱島東3丁目2番15号

6/18山口さんより情報提供。

**Comment by wankyo1010** [comment]
「20170618完成版」シートに反映しました
