### ISSUE TITLE
Bing Maps APIのKey

### ISSUE THREAD

**Issue by homata** [CodeforKohoku/papamama#6]
Bing Maps APIのKeyを港北用で取得する

**Comment by homata** [comment]
Bing Map API keyをこちらから取得する
https://msdn.microsoft.com/ja-jp/library/ff428642.aspx

MSのアカウントが必要です。
使用してもよい、メールアドレスか、SkypeのIDを教えてください

**Comment by chikarina** [comment]
okpyokohama2016@gmail.com

**Comment by homata** [comment]
@hatanakayumiko さんのアカウント(y-hatanaka@kohoku-drop.com)でBing API Keyを作成しました。

Application name	
CodeforKohoku_papamama	
Key:  <not show>
Application Url: 
Key type: Basic / Not-for-profit
Created date: 02/20/2017
Expiration date: None
Key Status: Enabled
<https://www.bingmapsportal.com/Application#>

commit git log
commit c4d275c860cbbcfe0c96d4b92ab6424b4f438f2f
Author: Hiroshi Omata <op.homata@gmail.com>
Date:   Mon Feb 20 22:05:29 2017 +0900
    Update Bing API key for Code for Kohoku
