### ISSUE TITLE
マップデータ入力シートの凡例修正

### ISSUE THREAD

**Issue by wankyo1010** [CodeforKohoku/papamama#60]
マップデータ入力シート（スプレッドシート）の凡例の修正が必要

1) Type(保育施設種別)
　　小規模保育事業、事業所内保育事業　→小規模・事業所内保育事業
　　家庭的保育事業　→横浜保育室
　　届出済認可外保育施設　→認可外保育施設

2) 6/18の作業日に新規追加となった項目を追記

**Comment by chikarina** [comment]
2018/1/18 　完了確認
