### ISSUE TITLE
マップデータ入力シートの入力に関して

### ISSUE THREAD

**Issue by wankyo1010** [CodeforKohoku/papamama#61]
マップデータ入力シート（スプレッドシート）への入力で、ルールの確認が必要

１）入力ルール
→ 半角、全角など決めたルールに基づいていないデータが多々ある
　（プルダウンリスト機能を使うことで整合性がとりやすくなるかも）
２）「課題」「URL参照サイト・優先順位」シートを作業ルールとして１つにまとめてはどうか？
３）作業用に作成したシートやメモは、不要になった時点で各自で削除する
４）「完成版」にデータをマージする場合は、他にだれも作業していないか確認した方がよい

**Comment by chikarina** [comment]
2018/1/18 　完了確認
