### ISSUE TITLE
(？)マーククリックでこちらもさっぽろ保育園マップのページに飛ぶ

### ISSUE THREAD

**Issue by homata** [CodeforKohoku/papamama#8]
(？)マークをクリックしたら何処に飛ばすべきか？

1. 保育園マップのポータルとして、そのまま札幌に飛ばす
2. 港北のFacebookにリンクを替える
　- Facebookを使ってない人でも閲覧できる場所があるのか？
3. GitHubのWiki
4. どろっぷのページ

**Comment by homata** [comment]
リンクをGitHubのWikiに飛ばすように変更する.
Reameの内容は村岡さんに相談をする。

**Comment by chikarina** [comment]
1)札幌を港北区に変更
2)？から飛んだ時に必要なものを追加
・お問合せ用アドレスを追記　okpyokohama2016@gmail.com

**Comment by wankyo1010** [comment]
1)はGitHubのWikiで良いのでしょうか？他の地域ではGitHubのCodeのREADME.mdに飛んでいます。
README.mdも修正が必要ですね。。。
また、facebookアカウントがないと参照できませんが、公開グループのリンクも付けますか？

**Comment by homata** [comment]
リンク先を「https://github.com/CodeforKohoku/papamama/」に変更し、README.mdのファイルの内容を変更した

commit 96240e6620003bef5d0367acefc7cf4a118cecb0
Author: Hiroshi Omata <op.homata@gmail.com>
Date:   Mon Feb 20 22:38:52 2017 +0900

    (?)のリンク先をGitHubのページに変更
