### ISSUE TITLE
データが重なって表示されない園がある

### ISSUE THREAD

**Issue by homata** [CodeforKohoku/papamama#9]
データが重なって表示されない園があるがどうするか？
-> 修正方法のルール作りをする

●園が被っていることで見えない
　プリンス幼稚園がない・・・。南日吉、
→どう表示するか検討

**Comment by kakikidrop** [comment]
・ペガサス保育園／ペガサス夜間保育園について
　※住所が同じなのでしょうがないが、アイコンが重なっていてペガサス保育園の詳細情報が見れない。

**Comment by ringostar130** [comment]
既存の園のみ作業完了
