### ISSUE TITLE
新設園の追加（港北区）

### ISSUE THREAD

**Issue by toon258** [CodeforKohoku/papamama#96]
今年度の新設園のデータを入力します

元データ：横浜市のHP
https://www.city.yokohama.lg.jp/kurashi/kosodate-kyoiku/hoiku-yoji/shisetsu/info/hoiku-ichiran/ninka-opendata.html

★わかる人へ確認★　新設園の見分け方がわかるページはありますか？

保育園リスト（データ入力シート） 
https://docs.google.com/spreadsheets/d/1HCCg2KcCZJubghX-846Y4K9P3EbKIA1mO2Pgv006kIg/edit?usp=sharing
→表示できない方は「権限のリクエスト」をお願いします
→入力先は「20210523作業」（オレンジのシート）です

**Comment by mijies** [comment]
新設園のデータについて少し整理させてください。

現在、保育園マップでは施設名「Name」に文字列"新設・仮称"が
含まれているかどうかで新設園か判定しています。

以下のような課題があります。
 - 新設園でなくすには施設名から"新設・仮称"を削除する作業
 - データが更新されないとずっと新設園のまま
 - 新設園でないと判断する基準が不明瞭
     -> 各施設の新設とこちらの更新タイミングで大きな開きがでます。

まずは以下の点を明確にしたいと思います。
 1 新設園の定量化できる基準の明確化(既にあるのかは不明です)
 2 データシートでの記載or判定方法
 3 マップアプリ側での判定方法

**Comment by mijies** [comment]
私の方で、とりあえずイメージがつくようにと上記に対する候補をあげてみます。

1 新設園の定量化できる基準の明確化(既にあるのかは不明です)
  -> 設立年月日が現在日より一年以内(or半年)

2 データシートでの記載or判定方法
　-> 上述の基準の場合、データシートに新設園の年月日を記述する項目を設ける
   　現在は「設立年度」という項目がありますが、年度での切り分けだとちょっとつらいかもですね。
   　なお、市側のデータでは「事業の開始年月日」という該当しそうな項目があります。

3 マップアプリ側での判定方法
　-> データシートの新設園の年月日のための項目の値(年月日)から基準と比較して判定

**Comment by mijies** [comment]
本日のもくもく会参加者の方々と相談した結果、新設園の基準は以下の通りとします。
・設立日が現在日より一年以内。　※月までの情報で判定
     （例）現在が2021年11月なら2020年12月までが新設園

データシートの更新は以下の通りです。
・現在入力データが存在しない「設立年度」の項目をあてる。
　入力フォーマットは設立年月としYYYYMM
　（例）設立が2021年11月の場合：202111  
　月が不明な場合は00とし、判定では暗黙で4月とする
　（例）202100  -> 202104として判定する
　データシートの項目名「設立年度」はひとまず維持し、
　マップアプリ側の改修準備が整った段階で項目名を更新する。

マップアプリへの反映タイミングについて、
・本日2021年11月のデータ入力までは、従来の「新設園・仮称」の方法で対応。
・マップアプリ側の改修準備が整った段階で、
　上述の基準とデータシートの入力データによる方針に切り替えする。

**Comment by mijies** [comment]
設立年度の項目はポップアップで以下のように表示する想定です。
202104の場合：2021年4月
202100の場合：2021年

年度表記ではなくなったので、設立年度の項目名は「Founded」へ変更したいなと思います。

**Comment by mijies** [comment]
2022/1/22の話し合いで設立年度の項目名は「設立年月」へ変更となりました。
